language: scala
dist: trusty
jdk:
  - oraclejdk11

scala:
  - 2.12.10

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: test
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 4.0.0
      script: 
        - sbt ++$TRAVIS_SCALA_VERSION check
        - sbt +test
        - sbt ++$TRAVIS_SCALA_VERSION makeMicrosite
      name: "Tests and scalafmt check"
    - stage: release
      before_install:
        - export PATH=${PATH}:./vendor/bundle
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 4.0.0
      script:
        - sbt ++$TRAVIS_SCALA_VERSION ci-release
        - sh scripts/publishMicrosite.sh
      name: "Release to sonatype and publish docs"


cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - $HOME/.rvm/
    - vendor/bundle

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - rm -rf $HOME/.ivy2/local

before_install:
  - git fetch --tags
