addSbtPlugin("org.scalameta"     % "sbt-scalafmt"   % "2.0.2")
addSbtPlugin("com.47deg"         % "sbt-microsites" % "0.9.2")
addSbtPlugin("com.geirsson"      % "sbt-ci-release" % "1.2.6")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.9.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"     % "5.3.1")
